---
title       : Developing Data Products Course Assignment
subtitle    : Feb 28th 2016
author      : Rajesh Gore
job         : Student
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
ext_widgets: {rCharts: [libraries/nvd3]}

---
## Overview

1. Intoduction to World Hunger statistics
2. Assignment details
3. Summary

--- .class #id 

## World Hunger statistics

The data used for this assignment is "hunger.csv"  data file from one of the Coursera course.
This data is used for assignment to Number of hungry children per year and per country.

```{r echo = F, results = 'asis'}
require(rCharts)
dt <- fread('data/hunger.csv') %>% mutate(SEX = tolower(SEX))
dt <- dt[order(dt$YEAR)]
sexType <- sort(unique(dt$SEX))
dt.agg.YEAR <- dt %>% 
  filter(YEAR >= 1999 , YEAR <= 2015) %>%
  group_by(YEAR) %>%  
  summarise_each(funs(sum), TCOUNT) 
   HByYear <- nPlot(
      TCOUNT ~ YEAR,
      data = dt.agg.YEAR,
      type = "multiBarChart", dom = "HungerCountByYear", width = 650
    )
     HByYear$chart(margin = list(left = 100))
     HByYear$yAxis( axisLabel = "Count", width = 80)
     HByYear$xAxis( axisLabel = "Year", width = 70)
    HByYear$print('chart1')
```

--- .class #id 

## Assignment details

Assignment is for developing as a shiny application for learning shiny package.
The application includes the following:

1. Input Year range in form of slider, Gender in form of checkbox and others widgets 
2. server.R contains the code for data processing and rendering data and plots for ui.R
3. This application has three tabs which show hunger count details by country, by year and also provides ability to view and download data.
4. All source code and related document are available on git hub server.


--- .class #id 

## Summary

Data show hungry children statistic for all countries from year 1990 to 2015.
Most countries very few hungry children compare to countries like Bangladesh.


